export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';

export const CREATE_LEVEL_SELECT = 'CREATE_LEVEL_SELECT';
export const SET_LEVEL = 'SET_LEVEL';
export const UPDATE_LEVEL_SELECT = 'UPDATE_LEVEL_SELECT';
export const READY_NEXT_LEVEL = 'READY_NEXT_LEVEL';

export const SET_PLAY_AREA = 'SET_PLAY_AREA';
export const SET_ENTRANCES = 'SET_ENTRANCES';
export const SET_PLAYER = 'SET_PLAYER';

export const UPDATE_PLAYER_POS = 'UPDATE_PLAYER_POS';
export const UPDATE_PLAYER_WALKING = 'UPDATE_PLAYER_WALKING';
export const DAMAGE_PLAYER = 'DAMAGE_PLAYER';

export const UPDATE_ENEMY_POS = 'UPDATE_ENEMY_POS';
export const DAMAGE_ENEMY = 'DAMAGE_ENEMY';
export const REMOVE_ENEMY = 'REMOVE_ENEMY';

export const INCREASE_SCORE = 'INCREASE_SCORE';
export const INCREASE_KILL_SCORE = 'INCREASE_KILL_SCORE';
export const CHANGE_AMMO_VALUE = 'CHANGE_AMMO_VALUE';

export const UPDATE_LEVEL_PICKUPS = 'UPDATE_LEVEL_PICKUPS';

export const CHANGE_GUN = 'CHANGE_GUN';

export const UPDATE_PLAYER_VALUE = 'UPDATE_PLAYER_VALUE';
export const UPDATE_PLAYER_LEVEL_STATUS = 'UPDATE_PLAYER_LEVEL_STATUS';

export const INCREMENT_WAVE = 'INCREMENT_WAVE'
